casino:
  messages:
    command-unknown: "Command du casino inconnue: {COMMAND}"
    casino-usage: "Commandes du casino: {SUBCOMMANDS}"
    casino-slot-usage: "Commandes de casino slot: {SLOTCOMMANDS}"
    casino-slot-delete-usage: "usage: /casino slot delete <id>"
    slot-machine-admin-error: "Une erreur est survenue (voir les logs)"
    slot-machine-screen-initiate-building: "Nouvelle machine à sous: placez un levier et un bloc qui sera la base de l'écran"
    slot-machine-created: "Nouvelle machine à sous créée avec l'id {SLOTMACHINEID}"
    slot-machine-creation-error: "erreur: La machine à sous n'a pas pu être créée (voir logs)"
    slot-machine-screen-built: "Écran construit"
    slot-machine-lever-not-found: "Échec: un levier est attendu"
    slot-machine-lever-already-registered: "Échec: le levier est déjà assigné à la machine às sous {SLOTMACHINEID}"
    slot-machine-lever-built: "Levier construit"
    slot-machine-lever-deleted: "Machine à sous {SLOTMACHINEID} détruite"
    slot-machine-deleted: "Machine à sous {SLOTMACHINEID} supprimée"
    slot-machine-user-error: "La machine à sous est enrayée, appelez un admin"
    slot-machine-already-playing: "{PLAYER} est déjà en train de jouer !"
    slot-machine-already-playing-self: "Vous êtes déjà en train de jouer !"
    slot-machine-player-too-poor: "Il vous faut au moins {PRICE}C$ pour jouer !"
    slot-machine-debit: "{PRICE}C$ mis en jeu !"
    slot-machine-gain: "Vous avez gagné {GAIN}C$ !"
mysql:
  host: "localhost"
  database: "casino_db"
  user: "root"
  password: "6T4uwQJnCiu28MVA"
world-name: "world"
